Gerenciador:
    Menu_Principal:

<Menu_Principal>:
    name: 'Menu_Principal'
    FloatLayout:
        orientation: 'vertical'       
        canvas:
            Color:
                rgba: 1,1,1,1
            Rectangle: 
                size: self.size
                pos: self.pos
            Color:
                rgba:1,0,0,1
            Rectangle:
                size: 400, 50 
                pos:0, 655
               
